wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701239429.970057
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
dataset_path:
  desc: null
  value: datasets
dataset_name:
  desc: null
  value: CIFAR10
image_size:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 128
mode:
  desc: null
  value: meshgrid
shuffle:
  desc: null
  value: fixed
size:
  desc: null
  value: 2
port:
  desc: null
  value: 29500
model:
  desc: null
  value: ResNet18
pretrained:
  desc: null
  value: 0
optimization:
  desc: null
  value: samprox
eta:
  desc: null
  value: 0.01
rho:
  desc: null
  value: 0.5
mu:
  desc: null
  value: 0.5
multiple_local_gossip:
  desc: null
  value: true
local_iter:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.1
wd:
  desc: null
  value: 0.0
gamma:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
warmup_step:
  desc: null
  value: 5
epoch:
  desc: null
  value: 300
early_stop:
  desc: null
  value: 5000
milestones:
  desc: null
  value:
  - 1000
  - 1500
  - 2000
  - 2500
seed:
  desc: null
  value: 777
device:
  desc: null
  value: 0
amp:
  desc: null
  value: false
gossip_step:
  desc: null
  value: 1500
using_efficient_scheme:
  desc: null
  value: false
identity:
  desc: null
  value: CIFAR10s32-bs128-meshgrid-fixed-n2-ResNet18-p0-lr0.1-5-epoch300-samprox_mgsStep_1500-mlg_True
logs_perf_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_perf
perf_data_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_perf/CIFAR10
perf_xlsx_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_perf/CIFAR10/xlsx
perf_imgs_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_perf/CIFAR10/imgs
perf_dict_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_perf/CIFAR10/dict
perf_best_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_perf/CIFAR10/best
logs_runs_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_runs
runs_data_dir:
  desc: null
  value: /home/junemun/code/DSAMConsensus/logs_runs/CIFAR10
